name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2
      
    - name: Build
      run: make build
      
    - name: Unit tests
      run: make test-unit
      
    - name: Archive test results
      uses: actions/upload-artifact@v3
      with:
        name: unit-test-results
        path: results/*.xml
      
    - name: API tests
      run: make test-api
      
    - name: Archive test results
      uses: actions/upload-artifact@v3
      with:
        name: api-test-results
        path: results/*.xml
      
    - name: End-to-end tests
      run: make test-e2e
      
    - name: Archive test results
      uses: actions/upload-artifact@v3
      with:
        name: e2e-test-results
        path: results/*.xml
      
    - name: Print logs
      run: |
        echo "Trabajo $GITHUB_WORKFLOW"
        echo "Ejecución número $GITHUB_RUN_NUMBER"
      
    - name: Publish JUnit test results
      uses: EnricoMi/publish-unit-test-result-action@v1
      with:
        files: results/*_result.xml
      
    - name: Send email on failure
      if: failure()
      run: |
        echo "El trabajo $GITHUB_WORKFLOW ha fallado en la ejecución número $GITHUB_RUN_NUMBER. Por favor, revisa los registros y toma las acciones necesarias." | mail -s "Pipeline fallido: $GITHUB_WORKFLOW #$GITHUB_RUN_NUMBER" admaigualca@gmail.com
