name: CI Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build
      run: make build

    - name: Unit tests
      run: make test-unit

    - name: Archive unit test results
      uses: actions/upload-artifact@v3
      with:
        name: unit-test-results
        path: results/*.xml

    - name: API tests
      run: make test-api

    - name: Archive API test results
      uses: actions/upload-artifact@v3
      with:
        name: api-test-results
        path: results/*.xml

    - name: End-to-end tests
      run: make test-e2e

    - name: Archive end-to-end test results
      uses: actions/upload-artifact@v3
      with:
        name: e2e-test-results
        path: results/*.xml

    - name: Print logs
      run: |
        echo "Trabajo: ${{ github.workflow }}"
        echo "Ejecución número: ${{ github.run_number }}"

  post:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download all workflow run artifacts
      uses: actions/download-artifact@v3

    - name: Publish Test Results
      uses: mikepenz/action-junit-report@v3
      with:
        report_paths: 'results/*_result.xml'

    - name: Send failure notification
      if: ${{ failure() }}
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.MAIL_USERNAME }}
        password: ${{ secrets.MAIL_PASSWORD }}
        subject: ${{ github.workflow }} #${{ github.run_number }}
        to: admaigualca@gmail.com
        body: El trabajo ${{ github.workflow }} ha fallado en la ejecución número ${{ github.run_number }}. Por favor, revisa los registros y toma las acciones necesarias.
